### ISSUE TITLE
how to full make full author-year citation using natbib and imsart-nameyear.bst?

### ISSUE THREAD

**Issue by jvpoulos** [vtex-soft/texsupport.ims-aoas#2]
The [style guide](https://imstat.org/journals-and-publications/annals-of-applied-statistics/annals-of-applied-statistics-manuscript-submission/) asks for the initial reference in each section to be full, e.g.,
Smith, Jones, and Roberts (1992) 

Usually with natbib, one could specify \citet* to get the full citation in text, or include longnamesfirst as an option when calling natbib, but those commands do not appear to work with this .bst file. 

I'm using the template latex files: https://vtex-soft.github.io/texsupport.ims-aoas/

Any help is appreciated -

**Comment by edgaras-sakuras** [comment]
Hello,

just simply use the form as it is provided by `imsart-nameyear.bst`, because it is used in the final production PDFs.

Anyway thanks for noticing this! I'll ask our production department about differences in the style guide and final PDFs.
